<?php

/**
 * @file
 * this module contains code which applies wysiwyg editor to summary field also
 * code has been taken from http://theunraveler.com/blog/2012/drupal-7-how-add-wysiwyg-editor-text-summary-field/
 */

/**
 * Implementation of hook_field_widget_form_alter().
 *
 * Add WYSIWYG treatment to textarea summary form items.
 */
function wysiwyg_summary_field_widget_form_alter(&$element, &$form_state, $context) {
  if (isset($element['summary'])) {
    drupal_add_css(drupal_get_path('module', 'wysiwyg_summary') . '/wysiwyg_summary.css');
    drupal_add_js(drupal_get_path('module', 'wysiwyg_summary') . '/wysiwyg_summary.js');
    $element['summary']['#type'] = 'text_format';
    $element['summary']['#format'] = $element['#format'];
  }
}

/**
 * Implements hook_field_attach_presave().
 */
function wysiwyg_summary_field_attach_presave($entity_type, $entity) {
  list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);

  foreach (field_info_instances($entity_type, $bundle) as $instance) {
    $field = field_info_field_by_id($instance['field_id']);
    $field_name = $field['field_name'];
    if ($field['type'] == 'text_with_summary' && !empty($entity->$field_name)) {
      $language = isset($entity->language) ? $entity->language : LANGUAGE_NONE;
      foreach ($entity->{$field_name}[$language] as $id => &$value) {
        if (isset($value['summary']) && is_array($value['summary'])) {
          $value['summary'] = $value['summary']['value'];
        }
      }
    }
  }
}